##  (C) Copyright 2014 Alvaro J. Genial (http://alva.ro)
##  Use, modification and distribution are subject to the Boost Software
##  License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
##  http://www.boost.org/LICENSE_1_0.txt).

language: cpp

compiler:
  - g++
  - clang++

before_install:
  - sudo apt-get install libboost-dev libboost-program-options-dev libboost-python-dev

script:
  # Prevent slow builds from dying by echoing something every 5 minutes.
  - (while true; do echo "=== I'm a little teapot ==="; sleep 300; done)&

  - echo "=== Building ==="
  - scons || exit 1 # -j 2
  - echo "=== Done ==="

  - echo "=== Running Test Harness ==="
  - ./test
  - echo "=== Done ==="

  - echo "=== Running Python Binding Tests ==="
  - mv python-synth.so tests/python/synth.so
  - ls tests/python/binding*.py | xargs -n 1 python
  - echo "=== Done ==="
