##  (C) Copyright 2014 Alvaro J. Genial (http://alva.ro)
##  Use, modification and distribution are subject to the Boost Software License, Version 1.0.
##  (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt).

language: cpp

# TODO: Add debug/non-debug build environments.

compiler:
  - g++
  - clang++

before_install:
  - sudo apt-get install libboost-dev libboost-program-options-dev libboost-python-dev

before_script:
  - sudo apt-get install valgrind
  # Prevent slow builds from dying by echoing something every 5 minutes:
  - (while true; do echo "=== I'm a little teapot ==="; sleep 300; done)&

script:
  - scons tests/harness.out && (tests/harness.out; valgrind --track-origins=yes tests/harness.out)
  - scons synth && tests/harness.sh
  - scons # Make sure every other target builds successfully.
  - sudo python setup.py install # FIXME: && python tests/harness.py (Segfaults only in Travis)
