##  (C) Copyright 2014 Alvaro J. Genial (http://alva.ro)
##  Use, modification and distribution are subject to the Boost Software License, Version 1.0.
##  (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt).

language: cpp

compiler:
  - g++
  - clang++

### TODO: Build environment with boost available.
### before_install:
###   - sudo apt-get install libboost-dev libboost-python-dev

before_script:
  - sudo apt-get install valgrind
  # Prevent slow builds from dying by echoing something every 5 minutes:
  - (while true; do echo "=== I'm a little teapot ==="; sleep 300; done)&

script:
  - scons CXX=$CXX CC=$CC compiler=$CC tests/harness.out && (tests/harness.out; valgrind --track-origins=yes tests/harness.out)
  - scons CXX=$CXX CC=$CC compiler=$CC synth && tests/harness.sh
  - scons CXX=$CXX CC=$CC compiler=$CC tests/synth.so && python tests/harness.py
  - scons CXX=$CXX CC=$CC compiler=$CC # Make sure every other target builds successfully.
  ### TODO: Re-enable once Travis bumps memory limits.
  ### - sudo python setup.py build
