##  (C) Copyright 2014 Alvaro J. Genial (http://alva.ro)
##  Use, modification and distribution are subject to the Boost Software
##  License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
##  http://www.boost.org/LICENSE_1_0.txt).

language: cpp

compiler:
  - g++
  - clang++

before_install:
  - sudo apt-get install libboost-dev libboost-program-options-dev libboost-python-dev

before_script:
  - sudo apt-get install gdb

script:
  # Prevent slow builds from dying by echoing something every 5 minutes.
  - (while true; do echo "=== I'm a little teapot ==="; sleep 300; done)&
  - scons debug=1 group=django && cat tests/debug.gdb | sudo gdb ./test
  ### - scons && ./test
  ### - sudo python setup.py install && ls tests/python/binding*.py | xargs -n 1 python
