##  (C) Copyright 2014 Alvaro J. Genial (http://alva.ro)
##  Use, modification and distribution are subject to the Boost Software License, Version 1.0.
##  (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt).

language: cpp

compiler:
  - g++
  - clang++

### TODO: Build environment with boost available.
### before_install:
###   - sudo apt-get install libboost-dev libboost-python-dev

before_script:
  - sudo apt-get update
  - sudo apt-get install valgrind

script:
  - travis_wait scons tests/harness.out && (tests/harness.out; valgrind --track-origins=yes tests/harness.out)
  - travis_wait scons synth && tests/harness.sh
  - if [ "$CXX" == "clang++"  ]; then scons tests/synth.so && python tests/harness.py; fi
  ### TODO: Re-enable once Travis bumps memory limits.
  ### - scons # Make sure every other target builds successfully.
  ### - sudo python setup.py build
